export const movementScheduledMock = {
  count: 2,
  rows: [
    {
      id: 789,
      credentialId: null,
      userId: "d4445940-7f7e-11ee-a6b7-fde45dab3929",
      ipUser: null,
      depositaccountId: 223359,
      originAmount: 100,
      currency: "EUR",
      destinationCurrency: "EUR",
      reasonId: 3,
      reasonDes: null,
      conceptTransfer: "",
      callBackUrl: null,
      serviceId: null,
      userReference: null,
      fiat: true,
      destinationCredentialId: null,
      notifyUser: null,
      initialTransactionState: null,
      paymentcardId: null,
      startScheduledDate: "2025-05-01T00:00:00.000Z",
      frecuency: 1,
      state: 1,
      nextDate: "2025-05-01T00:00:00.000Z",
      createdAt: "2025-04-22T02:20:14.596Z",
      updatedAt: "2025-04-22T02:20:14.596Z",
      depositaccount: {
        id: 223359,
        accountNumber: "jhon.doe@gmail.com",
        alias: "Jhon Doe",
        firstName: "JHON",
        lastName: "DOE",
        type: 9,
        office: null,
        countryDestination: {
          name: "España",
          slug: "ES",
        },
      },
      service: null,
      paymentcard: null,
    },
    {
      id: 790,
      credentialId: null,
      userId: "d4445940-7f7e-11ee-a6b7-fde45dab3929",
      ipUser: null,
      depositaccountId: 223359,
      originAmount: 500,
      currency: "EUR",
      destinationCurrency: "EUR",
      reasonId: 3,
      reasonDes: null,
      conceptTransfer: "Remesa familiar",
      callBackUrl: null,
      serviceId: null,
      userReference: null,
      fiat: true,
      destinationCredentialId: null,
      notifyUser: null,
      initialTransactionState: null,
      paymentcardId: null,
      startScheduledDate: "2025-05-03T00:00:00.000Z",
      frecuency: 2,
      state: 1,
      nextDate: "2025-05-03T00:00:00.000Z",
      createdAt: "2025-04-22T04:32:40.609Z",
      updatedAt: "2025-04-22T04:32:40.609Z",
      depositaccount: {
        id: 223359,
        accountNumber: "jhon.doe@gmail.com",
        alias: "Jhon Doe",
        firstName: "JHON",
        lastName: "DOE",
        type: 9,
        office: null,
        countryDestination: {
          name: "España",
          slug: "ES",
        },
      },
      service: null,
      paymentcard: null,
    },
  ],
  limit: 10,
  offset: "0",
}
