export const movements: Movement[] = [
  {
    id: "282cc169-87cb-40ed-ba2f-23a4ceb6b417",
    status: "pendingIn",
    creationDate: "2024-01-29T09:02:24.763Z",
    valueDate: "2025-01-02T07:27:40.655Z",
    description: "Somniculosus via depereo desino.",
    amount: {
      value: 693853,
      currency: "EUR",
    },
    destinationAmount: {
      value: 990624,
      currency: "USD",
    },
    commission: {
      value: 16708,
      currency: "USD",
    },
    exchangeRate: 1.46,
    movementType: "transfer",
    paymentMethod: "Credit Card",
    reference: "datos mockeados",
    product: "Tropipay",
    sender: "Little, Steuber and Schoen",
    recipient: "Saul Casper",
    charges: [
      {
        id: "1000",
        status: "pendingIn",
        email: "Monique_Feil46@yahoo.com",
        cardLast4: 8603,
        cardBIN: 5943,
        cardHolderName: "Miss Rosemarie Hansen",
        issuerBank: "Reynolds, Upton and Langworth",
        cardType: "credit",
        createdAt: "2024-12-02T06:05:36.257Z",
        errorCode: "20058 - Fraud Suspected",
        cardPan: "7772",
        clientName: "Felipa",
        clientLastName: "Howe",
        cardBrand: "Visa",
        state: "declined",
        cardExpirationDate: "7/27",
        cardCountry: "PY",
        clientIp: "81.37.198.217",
        clientEmail: "Hollie_Towne26@hotmail.com",
        clientAddress: "549 Rafael Ramp",
        source: "",
      },
      {
        id: "1000",
        status: "pendingIn",
        email: "Dario_Adams@gmail.com",
        cardLast4: 1665,
        cardBIN: 6669,
        cardHolderName: "Arlene Ritchie",
        issuerBank: "Cronin, Cummings and Davis",
        cardType: "credit",
        createdAt: "2024-10-12T04:53:21.476Z",
        errorCode: "20058 - Fraud Suspected",
        cardPan: "7805",
        clientName: "Magnus",
        clientLastName: "Bednar-Kreiger",
        cardBrand: "Mastercard",
        state: "declined",
        cardExpirationDate: "2/25",
        cardCountry: "UG",
        clientIp: "ccda:99db:cbc5:bf9b:d19d:7a13:0bed:2bf1",
        clientEmail: "Juana_Skiles78@hotmail.com",
        clientAddress: "7668 Market Square",
        source: "",
      },
    ],
  },
  {
    id: "ca61a700-ed60-4270-9875-1ab150fa82ae",
    status: "paid",
    creationDate: "2024-12-09T13:07:26.616Z",
    valueDate: "2025-01-01T21:27:18.922Z",
    description: "Accusator varietas qui contigo amplus.",
    amount: {
      value: 194983,
      currency: "EUR",
    },
    destinationAmount: {
      value: 492816,
      currency: "USD",
    },
    commission: {
      value: 522890,
      currency: "EUR",
    },
    exchangeRate: 0.79,
    movementType: "payment",
    paymentMethod: "Tropipay Balance",
    reference: "datos mockeados",
    product: "Tropipay",
    sender: "Dare - Crist",
    recipient: "Saul Casper",
    charges: [
      {
        id: "1000",
        status: "paid",
        email: "Aleen.Wolf@hotmail.com",
        cardLast4: 8108,
        cardBIN: 5064,
        cardHolderName: "Melanie Tremblay",
        issuerBank: "Johns, Stiedemann and Torp",
        cardType: "debit",
        createdAt: "2024-10-03T16:27:09.247Z",
        errorCode: "20058 - Fraud Suspected",
        cardPan: "6024",
        clientName: "Ross",
        clientLastName: "Stracke",
        cardBrand: "Mastercard",
        state: "approved",
        cardExpirationDate: "5/22",
        cardCountry: "BS",
        clientIp: "beca:d0eb:b8eb:ddca:7fde:7ad0:f72a:7ec5",
        clientEmail: "Kristoffer27@hotmail.com",
        clientAddress: "49198 Market Place",
        source: "",
      },
      {
        id: "1000",
        status: "paid",
        email: "Sabryna_Effertz17@gmail.com",
        cardLast4: 8090,
        cardBIN: 2515,
        cardHolderName: "Elizabeth Nitzsche",
        issuerBank: "Beahan, Kemmer and Fay",
        cardType: "credit",
        createdAt: "2024-01-14T03:47:26.636Z",
        errorCode: "20058 - Fraud Suspected",
        cardPan: "2187",
        clientName: "Louisa",
        clientLastName: "Johns",
        cardBrand: "Visa",
        state: "approved",
        cardExpirationDate: "12/26",
        cardCountry: "AL",
        clientIp: "36.96.109.237",
        clientEmail: "Bonita48@gmail.com",
        clientAddress: "1259 Reese Lane",
        source: "",
      },
      {
        id: "1000",
        status: "paid",
        email: "Kailyn.Sawayn@gmail.com",
        cardLast4: 5870,
        cardBIN: 1189,
        cardHolderName: "Terri Daugherty-Mayert",
        issuerBank: "Block, Price and Hodkiewicz",
        cardType: "credit",
        createdAt: "2024-10-02T10:38:08.640Z",
        errorCode: "20000 - Unknown Error",
        cardPan: "3256",
        clientName: "Maci",
        clientLastName: "Leannon",
        cardBrand: "Visa",
        state: "declined",
        cardExpirationDate: "3/23",
        cardCountry: "MX",
        clientIp: "06a0:8add:2f8e:46cc:9bfe:fd36:f0f1:d70e",
        clientEmail: "Edgar_Kub@hotmail.com",
        clientAddress: "76897 Madison Avenue",
        source: "",
      },
    ],
  },
  {
    id: "f30c6e64-0569-44a9-8d77-e1d4742e4447",
    status: "paid",
    creationDate: "2024-01-15T02:42:01.062Z",
    valueDate: "2025-01-01T21:29:28.222Z",
    description: "Accusator cerno alii timidus corporis voluntarius deripio.",
    amount: {
      value: 777843,
      currency: "EUR",
    },
    destinationAmount: {
      value: 19425,
      currency: "USD",
    },
    commission: {
      value: 686771,
      currency: "USD",
    },
    exchangeRate: 1.03,
    movementType: "payment",
    paymentMethod: "Tropipay Balance",
    reference: "datos mockeados",
    product: "woocommerce",
    sender: "Ebert, Konopelski and Hoeger",
    recipient: "Saul Casper",
    charges: [
      {
        id: "1000",
        status: "paid",
        email: "Omer29@hotmail.com",
        cardLast4: 7613,
        cardBIN: 9339,
        cardHolderName: "Mrs. Ramona Kshlerin",
        issuerBank: "Senger, Rutherford and Hamill",
        cardType: "credit",
        createdAt: "2024-05-31T15:28:06.894Z",
        errorCode: "20058 - Fraud Suspected",
        cardPan: "7808",
        clientName: "Naomi",
        clientLastName: "Krajcik",
        cardBrand: "Visa",
        state: "approved",
        cardExpirationDate: "7/28",
        cardCountry: "HU",
        clientIp: "246.123.69.194",
        clientEmail: "Dorian.Kuvalis@gmail.com",
        clientAddress: "364 Pine Street",
        source: "",
      },
    ],
  },
  {
    id: "ac45071a-33f2-4dcd-b9af-014b0683a2ee",
    status: "paid",
    creationDate: "2024-07-22T01:05:38.941Z",
    valueDate: "2025-01-01T21:14:30.402Z",
    description: "Combibo subseco fuga.",
    amount: {
      value: 161432,
      currency: "EUR",
    },
    destinationAmount: {
      value: 808993,
      currency: "EUR",
    },
    commission: {
      value: 492506,
      currency: "USD",
    },
    exchangeRate: 0.88,
    movementType: "transfer",
    paymentMethod: "GiftCard",
    reference: "0051c21b-f8a1-4cdc-861e-59d96abe8d76",
    product: "Tropipay",
    sender: "Maggio, Leffler and Cummerata",
    recipient: "Saul Casper",
    charges: [
      {
        id: "1000",
        status: "pendingIn",
        email: "Christopher.Lindgren66@hotmail.com",
        cardLast4: 7689,
        cardBIN: 7391,
        cardHolderName: "Lucas Vandervort",
        issuerBank: "Mitchell - Schoen",
        cardType: "credit",
        createdAt: "2024-12-30T10:46:57.470Z",
        errorCode: "20000 - Unknown Error",
        cardPan: "8594",
        clientName: "Retta",
        clientLastName: "Bins",
        cardBrand: "Visa",
        state: "approved",
        cardExpirationDate: "2/28",
        cardCountry: "NE",
        clientIp: "7c0f:a2ef:c76d:1ddf:1f2c:93a6:ddff:4cd2",
        clientEmail: "Emory93@yahoo.com",
        clientAddress: "44013 Leffler Junctions",
        source: "",
      },
    ],
  },
  {
    id: "d7838e28-43d5-4954-9528-c0f53cffeb4e",
    status: "paid",
    creationDate: "2024-02-16T20:22:46.743Z",
    valueDate: "2025-01-02T02:28:58.062Z",
    description: "Sustineo arbustum facilis spiritus.",
    amount: {
      value: 975113,
      currency: "EUR",
    },
    destinationAmount: {
      value: 959993,
      currency: "EUR",
    },
    commission: {
      value: 735327,
      currency: "USD",
    },
    exchangeRate: 0.93,
    movementType: "payment",
    paymentMethod: "GiftCard",
    reference: "a8fec409-6633-4530-9f95-167237192102",
    product: "Tropipay",
    sender: "Mann, Gerhold and Herman",
    recipient: "Saul Casper",
    charges: [
      {
        id: "1000",
        status: "pendingIn",
        email: "Deanna9@gmail.com",
        cardLast4: 8140,
        cardBIN: 9126,
        cardHolderName: "Evelyn McGlynn",
        issuerBank: "Lockman, Friesen and Predovic",
        cardType: "credit",
        createdAt: "2024-12-10T07:22:47.309Z",
        errorCode: "20058 - Fraud Suspected",
        cardPan: "2941",
        clientName: "Macey",
        clientLastName: "Toy",
        cardBrand: "Mastercard",
        state: "approved",
        cardExpirationDate: "2/29",
        cardCountry: "PL",
        clientIp: "223.69.36.129",
        clientEmail: "Alejandrin20@yahoo.com",
        clientAddress: "8645 Schultz Ville",
        source: "",
      },
      {
        id: "1000",
        status: "pendingIn",
        email: "Jovani70@gmail.com",
        cardLast4: 2901,
        cardBIN: 6976,
        cardHolderName: "Dr. Guillermo Treutel",
        issuerBank: "Nikolaus, Williamson and Wiza",
        cardType: "debit",
        createdAt: "2024-08-28T06:12:04.199Z",
        errorCode: "20000 - Unknown Error",
        cardPan: "1258",
        clientName: "Thelma",
        clientLastName: "Hudson",
        cardBrand: "Mastercard",
        state: "declined",
        cardExpirationDate: "11/24",
        cardCountry: "MW",
        clientIp: "6d8d:c862:48f1:c3e0:3ea7:5ee1:15b7:fb68",
        clientEmail: "Abbie_Ledner58@gmail.com",
        clientAddress: "4930 Nathen Motorway",
        source: "",
      },
      {
        id: "1000",
        status: "paid",
        email: "Micaela.Schaefer10@yahoo.com",
        cardLast4: 1822,
        cardBIN: 9673,
        cardHolderName: "Milton Friesen",
        issuerBank: "Walter LLC",
        cardType: "credit",
        createdAt: "2024-01-12T08:08:39.618Z",
        errorCode: "20058 - Fraud Suspected",
        cardPan: "8192",
        clientName: "Lawson",
        clientLastName: "Flatley",
        cardBrand: "Mastercard",
        state: "declined",
        cardExpirationDate: "8/22",
        cardCountry: "EE",
        clientIp: "b2e7:dafd:1d51:b0a5:cec1:8bcf:44bf:0114",
        clientEmail: "Adelbert.Wiza8@yahoo.com",
        clientAddress: "1210 Lansdowne Road",
        source: "",
      },
    ],
  },
  {
    id: "68f30f08-bbc1-4250-9206-f2451addd211",
    status: "pendingIn",
    creationDate: "2024-10-28T19:31:19.414Z",
    valueDate: "2025-01-02T05:30:48.714Z",
    description: "Conscendo vomer terminatio urbanus incidunt esse.",
    amount: {
      value: 86632,
      currency: "EUR",
    },
    destinationAmount: {
      value: 172088,
      currency: "USD",
    },
    commission: {
      value: 412930,
      currency: "USD",
    },
    exchangeRate: 1.11,
    movementType: "payment",
    paymentMethod: "Credit Card",
    reference: "229af16d-ea11-4a6b-ab91-cd2ce486bbc4",
    product: "Tropipay",
    sender: "Borer - Ward",
    recipient: "Saul Casper",
    charges: [
      {
        id: "1000",
        status: "pendingIn",
        email: "Maye_Botsford75@yahoo.com",
        cardLast4: 7100,
        cardBIN: 7513,
        cardHolderName: "Mindy Dare",
        issuerBank: "West, Murphy and Marquardt",
        cardType: "credit",
        createdAt: "2024-12-23T01:59:28.723Z",
        errorCode: "20000 - Unknown Error",
        cardPan: "9908",
        clientName: "Brielle",
        clientLastName: "Zulauf",
        cardBrand: "Mastercard",
        state: "declined",
        cardExpirationDate: "7/26",
        cardCountry: "BG",
        clientIp: "4.189.191.66",
        clientEmail: "Walton.Stanton@yahoo.com",
        clientAddress: "178 Reginald Isle",
        source: "",
      },
      {
        id: "1000",
        status: "paid",
        email: "Lempi.Jakubowski64@hotmail.com",
        cardLast4: 1002,
        cardBIN: 6915,
        cardHolderName: "Brandy Little",
        issuerBank: "Cruickshank - Rohan",
        cardType: "debit",
        createdAt: "2024-05-11T17:38:12.331Z",
        errorCode: "20058 - Fraud Suspected",
        cardPan: "1172",
        clientName: "Ellsworth",
        clientLastName: "Bartell",
        cardBrand: "Visa",
        state: "approved",
        cardExpirationDate: "6/28",
        cardCountry: "BE",
        clientIp: "208.66.64.93",
        clientEmail: "Laurine77@gmail.com",
        clientAddress: "536 Morissette Wall",
        source: "",
      },
    ],
  },
  {
    id: "032c0fbd-34f6-4d18-9feb-8407ae90ac3b",
    status: "pendingIn",
    creationDate: "2024-09-12T15:11:29.435Z",
    valueDate: "2025-01-02T02:20:02.196Z",
    description:
      "Copiose currus demitto sumptus sperno valde campana benigne tendo.",
    amount: {
      value: 888786,
      currency: "EUR",
    },
    destinationAmount: {
      value: 157707,
      currency: "EUR",
    },
    commission: {
      value: 344379,
      currency: "USD",
    },
    exchangeRate: 1.01,
    movementType: "payment",
    paymentMethod: "GiftCard",
    reference: "343ae398-2cf1-40bc-a883-0597d73ad689",
    product: "woocommerce",
    sender: "Lakin LLC",
    recipient: "Saul Casper",
    charges: [
      {
        id: "1000",
        status: "paid",
        email: "Davonte_Jaskolski3@gmail.com",
        cardLast4: 9505,
        cardBIN: 3843,
        cardHolderName: "Angie Heathcote",
        issuerBank: "Okuneva LLC",
        cardType: "credit",
        createdAt: "2024-09-09T11:22:40.784Z",
        errorCode: "20058 - Fraud Suspected",
        cardPan: "2326",
        clientName: "Eden",
        clientLastName: "Doyle",
        cardBrand: "Mastercard",
        state: "approved",
        cardExpirationDate: "2/24",
        cardCountry: "TT",
        clientIp: "167.189.159.47",
        clientEmail: "Blair81@hotmail.com",
        clientAddress: "44331 Cruickshank Mews",
        source: "",
      },
      {
        id: "1000",
        status: "pendingIn",
        email: "Haylie.Beahan@hotmail.com",
        cardLast4: 6352,
        cardBIN: 3632,
        cardHolderName: "Regina Schinner",
        issuerBank: "Reichel - Auer",
        cardType: "credit",
        createdAt: "2024-01-20T00:02:04.784Z",
        errorCode: "20058 - Fraud Suspected",
        cardPan: "6893",
        clientName: "Dejah",
        clientLastName: "Bergnaum",
        cardBrand: "Mastercard",
        state: "declined",
        cardExpirationDate: "6/25",
        cardCountry: "GE",
        clientIp: "ee0e:bdcc:d2db:abf6:51ca:eff8:002d:0fc8",
        clientEmail: "Jessika_Lockman@yahoo.com",
        clientAddress: "98385 E 5th Street",
        source: "",
      },
    ],
  },
  {
    id: "616b1523-b27b-4161-be6f-81153b410e16",
    status: "pendingIn",
    creationDate: "2024-01-25T06:13:31.818Z",
    valueDate: "2025-01-02T00:10:43.895Z",
    description:
      "Vomica delego arma arbitro sum administratio thymum antea trucido.",
    amount: {
      value: 504344,
      currency: "EUR",
    },
    destinationAmount: {
      value: 724175,
      currency: "USD",
    },
    commission: {
      value: 757074,
      currency: "EUR",
    },
    exchangeRate: 1.36,
    movementType: "transfer",
    paymentMethod: "Credit Card",
    reference: "a8b2e1b4-2f83-4cfb-8655-29cfe2067d16",
    product: "api",
    sender: "Hauck and Sons",
    recipient: "Saul Casper",
    charges: [
      {
        id: "1000",
        status: "paid",
        email: "Sammy_Mayert@gmail.com",
        cardLast4: 2553,
        cardBIN: 4984,
        cardHolderName: "Dr. Harold Osinski",
        issuerBank: "Erdman, Marvin and Bahringer",
        cardType: "debit",
        createdAt: "2024-11-01T20:08:40.265Z",
        errorCode: "20058 - Fraud Suspected",
        cardPan: "7816",
        clientName: "Idella",
        clientLastName: "Hettinger-Smith",
        cardBrand: "Mastercard",
        state: "approved",
        cardExpirationDate: "8/26",
        cardCountry: "ID",
        clientIp: "80.90.253.246",
        clientEmail: "Weldon.Spinka1@gmail.com",
        clientAddress: "69775 Marcia Ranch",
        source: "",
      },
      {
        id: "1000",
        status: "pendingIn",
        email: "Rebeca_Cormier22@gmail.com",
        cardLast4: 9325,
        cardBIN: 7883,
        cardHolderName: "Cheryl Swift",
        issuerBank: "Murazik, O'Keefe and Hilpert",
        cardType: "debit",
        createdAt: "2024-04-10T12:28:52.813Z",
        errorCode: "20058 - Fraud Suspected",
        cardPan: "3860",
        clientName: "Pablo",
        clientLastName: "Torp",
        cardBrand: "Mastercard",
        state: "approved",
        cardExpirationDate: "7/25",
        cardCountry: "CO",
        clientIp: "bdaf:1daa:5ce3:a0d0:fd8b:63a5:dfbb:9be2",
        clientEmail: "Orrin_Jacobson@hotmail.com",
        clientAddress: "5909 Devon Plain",
        source: "",
      },
    ],
  },
  {
    id: "e3efc6e8-338a-4664-b953-9bfb4aca87a7",
    status: "pendingIn",
    creationDate: "2024-06-02T11:07:13.515Z",
    valueDate: "2025-01-02T02:47:45.768Z",
    description: "Harum collum caute virtus baiulus.",
    amount: {
      value: 770188,
      currency: "EUR",
    },
    destinationAmount: {
      value: 231977,
      currency: "USD",
    },
    commission: {
      value: 221397,
      currency: "USD",
    },
    exchangeRate: 0.82,
    movementType: "transfer",
    paymentMethod: "Tropipay Balance",
    reference: "d6cfef53-6297-4055-996f-b3fa72ef6d2a",
    product: "Tropipay",
    sender: "Jaskolski Inc",
    recipient: "Saul Casper",
    charges: [
      {
        id: "1000",
        status: "paid",
        email: "Wilmer95@yahoo.com",
        cardLast4: 1814,
        cardBIN: 5383,
        cardHolderName: "Marion Schiller",
        issuerBank: "O'Reilly - Heller",
        cardType: "debit",
        createdAt: "2024-12-23T18:13:53.133Z",
        errorCode: "20058 - Fraud Suspected",
        cardPan: "5511",
        clientName: "Stephany",
        clientLastName: "Welch",
        cardBrand: "Mastercard",
        state: "approved",
        cardExpirationDate: "7/28",
        cardCountry: "MY",
        clientIp: "202.0.226.234",
        clientEmail: "Trever.Hahn33@gmail.com",
        clientAddress: "928 Janet Common",
        source: "",
      },
      {
        id: "1000",
        status: "paid",
        email: "Major24@gmail.com",
        cardLast4: 7815,
        cardBIN: 3052,
        cardHolderName: "Ms. Casey Lind",
        issuerBank: "Konopelski Inc",
        cardType: "credit",
        createdAt: "2024-03-28T18:20:59.755Z",
        errorCode: "20000 - Unknown Error",
        cardPan: "7390",
        clientName: "Jessica",
        clientLastName: "Brekke",
        cardBrand: "Mastercard",
        state: "approved",
        cardExpirationDate: "1/29",
        cardCountry: "MW",
        clientIp: "148.206.175.80",
        clientEmail: "Eriberto_OKon@gmail.com",
        clientAddress: "4632 Zola Alley",
        source: "",
      },
      {
        id: "1000",
        status: "paid",
        email: "Genesis_Rowe97@hotmail.com",
        cardLast4: 3197,
        cardBIN: 2107,
        cardHolderName: "Marilyn Rutherford-Huels",
        issuerBank: "Schneider, Bins and Quitzon",
        cardType: "credit",
        createdAt: "2024-05-20T12:06:12.663Z",
        errorCode: "20000 - Unknown Error",
        cardPan: "9701",
        clientName: "Maude",
        clientLastName: "Mayert",
        cardBrand: "Visa",
        state: "approved",
        cardExpirationDate: "5/25",
        cardCountry: "MW",
        clientIp: "46.143.208.202",
        clientEmail: "Edwina_Heathcote92@gmail.com",
        clientAddress: "52777 Marley Place",
        source: "",
      },
    ],
  },
  {
    id: "05f957ee-be95-4ec6-b064-daa35766d53d",
    status: "pendingIn",
    creationDate: "2024-08-20T14:45:15.576Z",
    valueDate: "2025-01-02T05:54:51.605Z",
    description:
      "Umerus adeo laborum cubitum quod libero delicate illo aeger adiuvo.",
    amount: {
      value: 332866,
      currency: "EUR",
    },
    destinationAmount: {
      value: 519489,
      currency: "USD",
    },
    commission: {
      value: 707921,
      currency: "USD",
    },
    exchangeRate: 1.08,
    movementType: "payment",
    paymentMethod: "Tropipay Balance",
    reference: "de4dfd24-42bc-4eb0-b88e-bde12deb4434",
    product: "api",
    sender: "Jacobi, Thiel and Botsford",
    recipient: "Saul Casper",
    charges: [
      {
        id: "1000",
        status: "pendingIn",
        email: "Shannon_Tromp@hotmail.com",
        cardLast4: 4830,
        cardBIN: 7785,
        cardHolderName: "Margarita Kulas",
        issuerBank: "Ruecker, Boyer and Wisozk",
        cardType: "debit",
        createdAt: "2024-04-11T01:42:50.834Z",
        errorCode: "20058 - Fraud Suspected",
        cardPan: "5285",
        clientName: "Emerson",
        clientLastName: "Wisoky",
        cardBrand: "Mastercard",
        state: "approved",
        cardExpirationDate: "4/28",
        cardCountry: "PG",
        clientIp: "142.42.79.249",
        clientEmail: "Elmore_Franecki49@hotmail.com",
        clientAddress: "3831 Christine Crest",
        source: "",
      },
      {
        id: "1000",
        status: "pendingIn",
        email: "Dorothea_Cronin7@gmail.com",
        cardLast4: 8325,
        cardBIN: 8237,
        cardHolderName: "Fannie Beer MD",
        issuerBank: "Morar - Berge",
        cardType: "debit",
        createdAt: "2024-12-29T06:40:35.348Z",
        errorCode: "20058 - Fraud Suspected",
        cardPan: "3636",
        clientName: "Colleen",
        clientLastName: "Leuschke",
        cardBrand: "Mastercard",
        state: "declined",
        cardExpirationDate: "6/26",
        cardCountry: "HU",
        clientIp: "2ace:aefe:4d3a:9dc5:77ba:cde3:2cab:6905",
        clientEmail: "Montana_McGlynn@gmail.com",
        clientAddress: "142 S Washington Street",
        source: "",
      },
    ],
  },
  {
    id: "6cb59c3c-e488-490c-901a-cda2035bfde6",
    status: "pendingIn",
    creationDate: "2024-09-11T12:01:09.396Z",
    valueDate: "2025-01-02T06:50:56.634Z",
    description: "Trans calcar defendo conspergo nihil defessus velum.",
    amount: {
      value: 935364,
      currency: "EUR",
    },
    destinationAmount: {
      value: 686818,
      currency: "EUR",
    },
    commission: {
      value: 649244,
      currency: "USD",
    },
    exchangeRate: 1.47,
    movementType: "transfer",
    paymentMethod: "Credit Card",
    reference: "datos mockeados",
    product: "Tropipay",
    sender: "Schuppe, Mann and Ernser",
    recipient: "Saul Casper",
    charges: [
      {
        id: "1000",
        status: "pendingIn",
        email: "Walton_VonRueden@hotmail.com",
        cardLast4: 5367,
        cardBIN: 6376,
        cardHolderName: "Roberto Braun DDS",
        issuerBank: "Mayer, Lindgren and Connelly",
        cardType: "debit",
        createdAt: "2024-02-11T19:59:39.270Z",
        errorCode: "20058 - Fraud Suspected",
        cardPan: "6483",
        clientName: "Darrick",
        clientLastName: "Streich",
        cardBrand: "Visa",
        state: "approved",
        cardExpirationDate: "4/28",
        cardCountry: "MX",
        clientIp: "226.6.225.117",
        clientEmail: "Lester.Champlin-Rolfson19@gmail.com",
        clientAddress: "639 Terrell Burg",
        source: "",
      },
      {
        id: "1000",
        status: "paid",
        email: "Tabitha19@gmail.com",
        cardLast4: 3992,
        cardBIN: 9997,
        cardHolderName: "Marguerite Kuhic",
        issuerBank: "Jacobi - King",
        cardType: "credit",
        createdAt: "2024-12-09T03:56:14.101Z",
        errorCode: "20058 - Fraud Suspected",
        cardPan: "3745",
        clientName: "Gloria",
        clientLastName: "Bayer",
        cardBrand: "Visa",
        state: "declined",
        cardExpirationDate: "5/27",
        cardCountry: "CF",
        clientIp: "b9ae:d82a:8edb:eb3c:69fb:25a0:6c70:d58c",
        clientEmail: "Gregory.Klein12@hotmail.com",
        clientAddress: "94296 Purdy Crossing",
        source: "",
      },
      {
        id: "1000",
        status: "paid",
        email: "Vito0@gmail.com",
        cardLast4: 3190,
        cardBIN: 8958,
        cardHolderName: "Claude Schmitt",
        issuerBank: "Halvorson - Dach",
        cardType: "credit",
        createdAt: "2024-08-03T14:24:53.911Z",
        errorCode: "20058 - Fraud Suspected",
        cardPan: "8515",
        clientName: "Twila",
        clientLastName: "Walsh",
        cardBrand: "Mastercard",
        state: "approved",
        cardExpirationDate: "3/27",
        cardCountry: "AO",
        clientIp: "6d17:e67d:dffd:a1e0:71cc:c0dc:a3d3:f6ed",
        clientEmail: "Veronica_Quigley48@hotmail.com",
        clientAddress: "7437 E 6th Avenue",
        source: "",
      },
    ],
  },
  {
    id: "fd795eca-81fb-4bc1-9aa1-174342dd3078",
    status: "pendingIn",
    creationDate: "2024-06-08T19:04:48.023Z",
    valueDate: "2025-01-02T15:37:21.201Z",
    description: "Aufero complectus voluptas.",
    amount: {
      value: 746223,
      currency: "EUR",
    },
    destinationAmount: {
      value: 122384,
      currency: "EUR",
    },
    commission: {
      value: 434333,
      currency: "EUR",
    },
    exchangeRate: 0.95,
    movementType: "refund",
    paymentMethod: "Credit Card",
    reference: "datos mockeados",
    product: "Tropipay",
    sender: "Koch, Haley and Kassulke",
    recipient: "Saul Casper",
    charges: [
      {
        id: "1000",
        status: "pendingIn",
        email: "Ova28@yahoo.com",
        cardLast4: 7781,
        cardBIN: 6331,
        cardHolderName: "Vanessa Jakubowski III",
        issuerBank: "Roob, Murazik and Wiza",
        cardType: "credit",
        createdAt: "2024-06-19T07:16:51.828Z",
        errorCode: "20058 - Fraud Suspected",
        cardPan: "3661",
        clientName: "Arnoldo",
        clientLastName: "Ratke",
        cardBrand: "Mastercard",
        state: "approved",
        cardExpirationDate: "10/27",
        cardCountry: "RE",
        clientIp: "72.126.40.193",
        clientEmail: "Lenora_Brekke65@hotmail.com",
        clientAddress: "8164 Davion Estates",
        source: "",
      },
      {
        id: "1000",
        status: "paid",
        email: "Carley.Schaden@hotmail.com",
        cardLast4: 8185,
        cardBIN: 5139,
        cardHolderName: "Cheryl Kassulke",
        issuerBank: "Schowalter and Sons",
        cardType: "debit",
        createdAt: "2024-09-14T00:11:39.593Z",
        errorCode: "20000 - Unknown Error",
        cardPan: "3816",
        clientName: "Maddison",
        clientLastName: "Gleason",
        cardBrand: "Visa",
        state: "declined",
        cardExpirationDate: "4/27",
        cardCountry: "GY",
        clientIp: "82.158.161.138",
        clientEmail: "Elena.Hettinger@yahoo.com",
        clientAddress: "365 Market Place",
        source: "",
      },
      {
        id: "1000",
        status: "pendingIn",
        email: "Keeley_Johnston81@hotmail.com",
        cardLast4: 5418,
        cardBIN: 7072,
        cardHolderName: "Hattie Howe",
        issuerBank: "Zieme - Moore",
        cardType: "debit",
        createdAt: "2024-06-10T18:21:43.960Z",
        errorCode: "20058 - Fraud Suspected",
        cardPan: "6044",
        clientName: "Linnea",
        clientLastName: "Kerluke",
        cardBrand: "Visa",
        state: "declined",
        cardExpirationDate: "2/26",
        cardCountry: "OM",
        clientIp: "52.4.121.93",
        clientEmail: "Dion86@gmail.com",
        clientAddress: "7357 N Jefferson Street",
        source: "",
      },
    ],
  },
  {
    id: "c12ea57a-2305-4afc-9a5c-04680aeabb15",
    status: "paid",
    creationDate: "2024-04-09T23:27:53.181Z",
    valueDate: "2025-01-01T18:08:42.739Z",
    description:
      "Claro reprehenderit clarus alter coma tremo tabgo aegrotatio bos vita.",
    amount: {
      value: 668217,
      currency: "EUR",
    },
    destinationAmount: {
      value: 731374,
      currency: "USD",
    },
    commission: {
      value: 194931,
      currency: "USD",
    },
    exchangeRate: 0.97,
    movementType: "payment",
    paymentMethod: "Tropipay Balance",
    reference: "b6e4c8a3-b4df-44a3-b0aa-7976ed37c95b",
    product: "woocommerce",
    sender: "Huels, Harvey and Ernser",
    recipient: "Saul Casper",
    charges: [
      {
        id: "1000",
        status: "pendingIn",
        email: "Mauricio.Boyle@gmail.com",
        cardLast4: 3111,
        cardBIN: 3387,
        cardHolderName: "Erika Sawayn",
        issuerBank: "Wolf - Legros",
        cardType: "debit",
        createdAt: "2024-05-21T02:25:07.212Z",
        errorCode: "20058 - Fraud Suspected",
        cardPan: "5512",
        clientName: "Trey",
        clientLastName: "Davis",
        cardBrand: "Visa",
        state: "declined",
        cardExpirationDate: "8/22",
        cardCountry: "DE",
        clientIp: "201.66.240.177",
        clientEmail: "Cassandre44@gmail.com",
        clientAddress: "3969 Court Street",
        source: "",
      },
    ],
  },
  {
    id: "4848b410-93f4-45f4-89a2-6fc64591c47c",
    status: "pendingIn",
    creationDate: "2024-08-08T23:17:50.269Z",
    valueDate: "2025-01-02T06:56:39.440Z",
    description: "Terga atavus pel cui tego carbo spectaculum.",
    amount: {
      value: 385177,
      currency: "EUR",
    },
    destinationAmount: {
      value: 768722,
      currency: "USD",
    },
    commission: {
      value: 867391,
      currency: "USD",
    },
    exchangeRate: 0.74,
    movementType: "transfer",
    paymentMethod: "Credit Card",
    reference: "18e88056-3ac8-4b98-bd19-c56af58af206",
    product: "Tropipay",
    sender: "Waelchi - Swift",
    recipient: "Saul Casper",
    charges: [
      {
        id: "1000",
        status: "pendingIn",
        email: "Jamarcus72@gmail.com",
        cardLast4: 1954,
        cardBIN: 3947,
        cardHolderName: "Fred Marvin",
        issuerBank: "Farrell, Hansen and Adams",
        cardType: "debit",
        createdAt: "2024-01-15T06:39:00.844Z",
        errorCode: "20000 - Unknown Error",
        cardPan: "9628",
        clientName: "Harold",
        clientLastName: "Botsford",
        cardBrand: "Visa",
        state: "declined",
        cardExpirationDate: "8/26",
        cardCountry: "PW",
        clientIp: "a0ff:d4be:446f:59d4:ec22:96bc:df4f:94cb",
        clientEmail: "Kali_Ullrich@hotmail.com",
        clientAddress: "792 Lonny Drives",
        source: "",
      },
      {
        id: "1000",
        status: "pendingIn",
        email: "Leann.Von@yahoo.com",
        cardLast4: 7978,
        cardBIN: 2566,
        cardHolderName: "Mrs. Vickie Borer",
        issuerBank: "D'Amore Group",
        cardType: "debit",
        createdAt: "2024-12-11T15:29:14.041Z",
        errorCode: "20058 - Fraud Suspected",
        cardPan: "6515",
        clientName: "Glenna",
        clientLastName: "Zulauf",
        cardBrand: "Visa",
        state: "declined",
        cardExpirationDate: "8/29",
        cardCountry: "CN",
        clientIp: "172.199.63.44",
        clientEmail: "Angeline.Tillman29@yahoo.com",
        clientAddress: "652 Nat Squares",
        source: "",
      },
    ],
  },
  {
    id: "eae15a0e-585b-4b11-a931-8e4b7409183e",
    status: "paid",
    creationDate: "2024-06-11T07:01:21.433Z",
    valueDate: "2025-01-02T16:06:30.746Z",
    description: "Abstergo strues repellendus.",
    amount: {
      value: 27176,
      currency: "EUR",
    },
    destinationAmount: {
      value: 579246,
      currency: "EUR",
    },
    commission: {
      value: 9225,
      currency: "EUR",
    },
    exchangeRate: 1.13,
    movementType: "refund",
    paymentMethod: "Tropipay Balance",
    reference: "208f3cc6-e949-4846-afd4-4e7d7c76367f",
    product: "Tropipay",
    sender: "Buckridge, Schowalter and Orn",
    recipient: "Saul Casper",
    charges: [
      {
        id: "1000",
        status: "paid",
        email: "Toy.Haag20@yahoo.com",
        cardLast4: 7292,
        cardBIN: 8402,
        cardHolderName: "Dr. Christine Botsford",
        issuerBank: "Legros Inc",
        cardType: "credit",
        createdAt: "2024-07-30T16:22:27.911Z",
        errorCode: "20000 - Unknown Error",
        cardPan: "5920",
        clientName: "Wilhelm",
        clientLastName: "Dach",
        cardBrand: "Visa",
        state: "declined",
        cardExpirationDate: "9/28",
        cardCountry: "BL",
        clientIp: "121.66.3.18",
        clientEmail: "Joan_Stanton-Altenwerth@hotmail.com",
        clientAddress: "54886 S Water Street",
        source: "",
      },
      {
        id: "1000",
        status: "paid",
        email: "Fredy.Cole62@gmail.com",
        cardLast4: 8997,
        cardBIN: 8958,
        cardHolderName: "Dixie Balistreri Sr.",
        issuerBank: "Konopelski - Nicolas",
        cardType: "credit",
        createdAt: "2024-01-27T03:01:02.974Z",
        errorCode: "20058 - Fraud Suspected",
        cardPan: "3249",
        clientName: "Kirstin",
        clientLastName: "McCullough",
        cardBrand: "Visa",
        state: "declined",
        cardExpirationDate: "7/23",
        cardCountry: "IE",
        clientIp: "197.54.75.190",
        clientEmail: "Berta63@gmail.com",
        clientAddress: "291 N Jackson Street",
        source: "",
      },
    ],
  },
  {
    id: "e9d12c94-de24-415d-b756-6211b410bc93",
    status: "pendingIn",
    creationDate: "2024-01-07T12:08:44.555Z",
    valueDate: "2025-01-02T09:20:13.008Z",
    description: "Vos fuga vergo color acceptus pariatur adiuvo.",
    amount: {
      value: 855013,
      currency: "EUR",
    },
    destinationAmount: {
      value: 663859,
      currency: "EUR",
    },
    commission: {
      value: 999385,
      currency: "EUR",
    },
    exchangeRate: 0.67,
    movementType: "payment",
    paymentMethod: "Credit Card",
    reference: "349cd2ff-29a3-49f4-bc99-e435645b2af9",
    product: "Tropipay",
    sender: "Breitenberg and Sons",
    recipient: "Saul Casper",
    charges: [
      {
        id: "1000",
        status: "pendingIn",
        email: "Lori_Rice@gmail.com",
        cardLast4: 9926,
        cardBIN: 8534,
        cardHolderName: "Mr. Rex Kerluke",
        issuerBank: "Legros - Runte",
        cardType: "credit",
        createdAt: "2024-07-22T14:59:06.633Z",
        errorCode: "20000 - Unknown Error",
        cardPan: "9884",
        clientName: "Tad",
        clientLastName: "Wyman",
        cardBrand: "Visa",
        state: "declined",
        cardExpirationDate: "5/26",
        cardCountry: "JO",
        clientIp: "170.136.140.36",
        clientEmail: "Neil.Swaniawski@hotmail.com",
        clientAddress: "86466 12th Street",
        source: "",
      },
      {
        id: "1000",
        status: "pendingIn",
        email: "Kasey_Kozey95@yahoo.com",
        cardLast4: 4290,
        cardBIN: 4252,
        cardHolderName: "Cecil Jacobson",
        issuerBank: "Davis, Walsh and Breitenberg",
        cardType: "debit",
        createdAt: "2024-03-03T11:13:09.265Z",
        errorCode: "20000 - Unknown Error",
        cardPan: "5518",
        clientName: "Magdalena",
        clientLastName: "Marvin",
        cardBrand: "Visa",
        state: "declined",
        cardExpirationDate: "1/27",
        cardCountry: "BD",
        clientIp: "73.16.117.57",
        clientEmail: "Vesta42@gmail.com",
        clientAddress: "67002 Hermann Flats",
        source: "",
      },
    ],
  },
  {
    id: "a17d3eec-887e-4384-bf82-c700b478bfe2",
    status: "paid",
    creationDate: "2024-09-06T21:09:15.825Z",
    valueDate: "2025-01-02T11:16:54.798Z",
    description: "Delinquo brevis crur summa bibo bos suscipit basium tondeo.",
    amount: {
      value: 127791,
      currency: "EUR",
    },
    destinationAmount: {
      value: 876866,
      currency: "EUR",
    },
    commission: {
      value: 155896,
      currency: "USD",
    },
    exchangeRate: 1.32,
    movementType: "transfer",
    paymentMethod: "GiftCard",
    reference: "b2fcc43c-11c8-484f-a0f6-39ea25598c7e",
    product: "woocommerce",
    sender: "Schowalter, Schaefer and Huels",
    recipient: "Saul Casper",
    charges: [
      {
        id: "1000",
        status: "pendingIn",
        email: "August_Wehner@gmail.com",
        cardLast4: 8938,
        cardBIN: 6051,
        cardHolderName: "Angelica Braun I",
        issuerBank: "Stark - Walker",
        cardType: "debit",
        createdAt: "2024-05-09T00:52:27.320Z",
        errorCode: "20000 - Unknown Error",
        cardPan: "9716",
        clientName: "Deion",
        clientLastName: "Heller",
        cardBrand: "Visa",
        state: "declined",
        cardExpirationDate: "1/27",
        cardCountry: "CC",
        clientIp: "d7e7:ac68:675f:9af5:2726:3c0e:9e35:f28b",
        clientEmail: "Alize65@yahoo.com",
        clientAddress: "583 W Central Avenue",
        source: "",
      },
      {
        id: "1000",
        status: "paid",
        email: "Marie.Block@yahoo.com",
        cardLast4: 2879,
        cardBIN: 9158,
        cardHolderName: "Ronnie Larkin",
        issuerBank: "Lueilwitz Group",
        cardType: "credit",
        createdAt: "2024-12-28T03:10:04.277Z",
        errorCode: "20058 - Fraud Suspected",
        cardPan: "4194",
        clientName: "Domenick",
        clientLastName: "Torp",
        cardBrand: "Mastercard",
        state: "approved",
        cardExpirationDate: "7/29",
        cardCountry: "MC",
        clientIp: "34.28.131.176",
        clientEmail: "Hermina_Turner3@yahoo.com",
        clientAddress: "51817 Lincoln Street",
        source: "",
      },
    ],
  },
  {
    id: "d99be6da-535b-44eb-a3b8-88cdf53ab47e",
    status: "pendingIn",
    creationDate: "2024-03-12T20:37:07.642Z",
    valueDate: "2025-01-02T13:41:57.821Z",
    description: "Tergeo admiratio clamo.",
    amount: {
      value: 237297,
      currency: "EUR",
    },
    destinationAmount: {
      value: 687933,
      currency: "USD",
    },
    commission: {
      value: 130201,
      currency: "EUR",
    },
    exchangeRate: 1.5,
    movementType: "transfer",
    paymentMethod: "Tropipay Balance",
    reference: "b6e93a92-d431-4eea-b77b-7a877cb723ea",
    product: "Tropipay",
    sender: "Simonis - Mraz",
    recipient: "Saul Casper",
    charges: [
      {
        id: "1000",
        status: "pendingIn",
        email: "Cecilia.Torp@yahoo.com",
        cardLast4: 2367,
        cardBIN: 6456,
        cardHolderName: "Lindsey Hermiston",
        issuerBank: "Kirlin - Nicolas",
        cardType: "debit",
        createdAt: "2024-03-16T22:43:58.963Z",
        errorCode: "20000 - Unknown Error",
        cardPan: "5146",
        clientName: "Amber",
        clientLastName: "Rogahn",
        cardBrand: "Mastercard",
        state: "declined",
        cardExpirationDate: "4/25",
        cardCountry: "SM",
        clientIp: "24a2:9bd2:cdf9:b066:2c18:57ef:fe75:6c4b",
        clientEmail: "Else_Robel@gmail.com",
        clientAddress: "12769 Pfeffer Ways",
        source: "",
      },
    ],
  },
  {
    id: "abe55cb9-4326-4e8b-aabb-3df942d9a1b7",
    status: "pendingIn",
    creationDate: "2024-05-13T07:43:30.927Z",
    valueDate: "2025-01-02T00:30:26.333Z",
    description: "Vociferor barba ver suadeo defleo subnecto astrum esse.",
    amount: {
      value: 344857,
      currency: "EUR",
    },
    destinationAmount: {
      value: 169584,
      currency: "EUR",
    },
    commission: {
      value: 82178,
      currency: "EUR",
    },
    exchangeRate: 1.21,
    movementType: "payment",
    paymentMethod: "GiftCard",
    reference: "f120a419-738c-4477-906d-23af04405d97",
    product: "api",
    sender: "Von - Langosh",
    recipient: "Saul Casper",
    charges: [
      {
        id: "1000",
        status: "pendingIn",
        email: "Abagail26@yahoo.com",
        cardLast4: 7197,
        cardBIN: 8340,
        cardHolderName: "Dr. Jesse Halvorson IV",
        issuerBank: "Breitenberg Inc",
        cardType: "debit",
        createdAt: "2024-09-04T19:17:12.593Z",
        errorCode: "20058 - Fraud Suspected",
        cardPan: "8297",
        clientName: "Owen",
        clientLastName: "Homenick",
        cardBrand: "Mastercard",
        state: "approved",
        cardExpirationDate: "3/29",
        cardCountry: "AU",
        clientIp: "249.154.49.124",
        clientEmail: "Osvaldo42@hotmail.com",
        clientAddress: "9948 Katharina Fort",
        source: "",
      },
    ],
  },
  {
    id: "184b052d-8c16-46e5-b31c-66ae6be8e472",
    status: "pendingIn",
    creationDate: "2024-04-09T00:01:17.577Z",
    valueDate: "2025-01-02T13:46:28.821Z",
    description: "Collum est vehemens praesentium sumo territo.",
    amount: {
      value: 670923,
      currency: "EUR",
    },
    destinationAmount: {
      value: 176028,
      currency: "EUR",
    },
    commission: {
      value: 550906,
      currency: "EUR",
    },
    exchangeRate: 0.53,
    movementType: "payment",
    paymentMethod: "Credit Card",
    reference: "413b4412-21e2-44f9-91ad-0ad7081b89ed",
    product: "api",
    sender: "Aufderhar, Heaney and Bogan",
    recipient: "Saul Casper",
    charges: [
      {
        id: "1000",
        status: "pendingIn",
        email: "Sigurd_Parisian58@gmail.com",
        cardLast4: 8075,
        cardBIN: 6286,
        cardHolderName: "Georgia Predovic",
        issuerBank: "Lind, Bailey and Shanahan",
        cardType: "debit",
        createdAt: "2024-04-02T16:52:04.992Z",
        errorCode: "20000 - Unknown Error",
        cardPan: "3102",
        clientName: "Hailee",
        clientLastName: "Mohr",
        cardBrand: "Visa",
        state: "approved",
        cardExpirationDate: "1/22",
        cardCountry: "BF",
        clientIp: "23.77.220.78",
        clientEmail: "Queenie42@gmail.com",
        clientAddress: "3347 Nelson Street",
        source: "",
      },
      {
        id: "1000",
        status: "pendingIn",
        email: "Chelsea87@yahoo.com",
        cardLast4: 3428,
        cardBIN: 2492,
        cardHolderName: "Mr. Patrick Rogahn",
        issuerBank: "Mante - Hammes",
        cardType: "debit",
        createdAt: "2024-04-13T00:26:48.666Z",
        errorCode: "20058 - Fraud Suspected",
        cardPan: "2658",
        clientName: "Janiya",
        clientLastName: "Welch",
        cardBrand: "Mastercard",
        state: "approved",
        cardExpirationDate: "8/29",
        cardCountry: "JM",
        clientIp: "d7c0:cb7e:7fbb:c5de:fdda:fddb:eaba:4794",
        clientEmail: "Herman.Carroll@gmail.com",
        clientAddress: "6353 Lillie Roads",
        source: "",
      },
    ],
  },
]
